### ISSUE TITLE
Version Mismatch -> Poker exercise. 

### ISSUE THREAD

**Issue by marvinbelfort** [exercism/rust-test-runner#62]
I tried 12 combinations on Cargo.toml, from 

```toml
[dependencies]
regex = "1" 
itertools = "0.10.5"
rand = "0.8.5"
lazy_static = "1.4.0"
```
to

```toml
[dependencies]
regex = "=1.5.5" 
itertools = "=0.10.3"
rand = "=0.8.5"
lazy_static = "=1.4.0"
either = "=1.6.1"
libc = "=0.2.125"
```
but none seemed to satisfy the required dependencies online.

```
We received the following error when we ran your code:
error: failed to select a version for the requirement `rand_core = "^0.6.0"` (locked to 0.6.4)
candidate versions found which didn't match: 0.6.3, 0.5.1, 0.4.2, ...
location searched: `/opt/test-runner/local-registry` index (which is replacing registry `crates-io`)
required by package `rand v0.8.5`
    ... which satisfies dependency `rand = "=0.8.5"` (locked to 0.8.5) of package `poker v1.1.0 (/mnt/exercism-iteration)`
perhaps a crate was updated and forgotten to be re-vendored?
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
```
my profile:
https://exercism.org/profiles/marvinbelfort
